annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Move identity remaining env vars to config"
    - kind: changed
      description: "Parametrized hard-coded identity auth vars"
    - kind: fixed
      description: "Identity secret should be referenced"
    - kind: fixed
      description: "Zeebe gateway incorrect rest ingress path"
    - kind: fixed
      description: "Set optimize global elasticsearch prefix"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/links: |
    - name: Camunda 8 docs
      url: https://docs.camunda.io/
    - name: Camunda 8 Self-Managed docs
      url: https://docs.camunda.io/docs/self-managed/about-self-managed/
    - name: Camunda 8 Self-Managed Helm charts
      url: https://github.com/camunda/camunda-platform-helm
  camunda.io/helmCLIVersion: 3.16.2
apiVersion: v2
appVersion: 8.6.x
dependencies:
- alias: identityKeycloak
  condition: identity.keycloak.enabled,identityKeycloak.enabled
  name: keycloak
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 22.2.6
- alias: identityPostgresql
  condition: identity.postgresql.enabled,identityPostgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 15.x.x
- alias: postgresql
  condition: postgresql.enabled
  name: web-modeler-postgresql
  repository: file://../web-modeler-postgresql-15
  version: 15.x.x
- condition: elasticsearch.enabled
  name: elasticsearch
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 21.3.22
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.x.x
description: 'Camunda 8 Self-Managed Helm charts. Camunda''s process automation platform
  allows developers to design, automate and improve processes. '
home: https://docs.camunda.io/docs/self-managed/overview/
icon: https://helm.camunda.io/imgs/camunda.svg
keywords:
- bpm
- bpmn
- camunda-platform
- dmn
- process-engine
- workflow
maintainers:
- email: ahmed.abouzaid@camunda.com
  name: aabouzaid
- email: daniel.rodriguez@camunda.com
  name: drodriguez-305
- email: hamza.masood@camunda.com
  name: hamza-m-masood
- email: jesse.simpson@camunda.com
  name: jessesimpson36
name: camunda-platform
sources:
- https://github.com/camunda/camunda-platform-helm
type: application
version: 11.0.2
