apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-mkcr
  namespace: db
  labels:
    app: mkcr-db
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: mkcr-db
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mkcr-db
      namespace: db
    spec:
      affinity: {}
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: admin
          image: mysql:5.6
          imagePullPolicy: IfNotPresent
          name: mysql
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: db-mkcr-evid
