apiVersion: v1
kind: Service
metadata:
  name: mkcr-db 
spec:
  type: NodePort
  ports:
    - name: mysql
      nodePort: 30306
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mkcr-db
